name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Run Environment 
        run: npm run dev
